ingress:
  dns:
  redirectDns:
  enableSSL:
  certIssuer:

images:
  backend:
  frontend:

service:
  type: ClusterIP
  port: 8443

postgres:
  database: gateway
  username: admin
  password: changeme
  volume_size: "2Gi"
  number_instances_postgres: 1
  logical_backup: false

number_instances_backend: 1