ingress:
  dns: terminology.services.base4nfdi.de
  dnsAlias: ts4nfdi-api-gateway.prod.km.k8s.zbmed.de
  enableSSL:
  certIssuer:
images:
  frontend: syphax0/api-gateway:develop

gateway:
  admin_password: changeme
  jwt_secret: changeme

service:
  type: ClusterIP
  port: 8443

postgres:
  storage: 1Gi
  database: gateway
  username: admin
  password: changeme
