apiVersion: v1
kind: Secret
metadata:
  name: postgres-wal-s3
  namespace: ts4nfdi
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ENDPOINT: "https://s3.de-west-1.psmanaged.com"
  AWS_REGION: "de-west-1"
  USE_WALG: "true"