apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.images.frontend }}
        env:
          - name: ONTOPORTAL_APIKEY
            valueFrom:
              secretKeyRef:
                name: ontoportal-secret
                key: ONTOPORTAL_APIKEY
        ports:
          - containerPort: 8080
