apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.number_instances_backend }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-backend
        project: ts4nfdi
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: ts4nfdi-gateway
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-postgres 5432; do echo waiting for postgres; sleep 2; done' ]
      containers:
        - name: api-gateway
          image: {{ .Values.images.backend }}
          env:
            - name: ONTOPORTAL_APIKEY
              valueFrom:
                secretKeyRef:
                  name: ontoportal-secret
                  key: ONTOPORTAL_APIKEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.database }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-password
                  key: ADMIN_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-client-secret
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: oidc-client-id
                  key: OIDC_CLIENT_ID
            - name: OIDC_AUTHORITY
              valueFrom:
                configMapKeyRef:
                  name: oidc-authority
                  key: OIDC_AUTHORITY
            - name: OIDC_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: oidc-issuer
                  key: OIDC_ISSUER
            - name: OIDC_AUTHORIZATION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: oidc-authorization-endpoint
                  key: OIDC_AUTHORIZATION_ENDPOINT
            - name: OIDC_TOKEN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: oidc-token-endpoint
                  key: OIDC_TOKEN_ENDPOINT
            - name: OIDC_USERINFO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: oidc-userinfo-endpoint
                  key: OIDC_USERINFO_ENDPOINT
            - name: OIDC_END_SESSION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: oidc-end-session-endpoint
                  key: OIDC_END_SESSION_ENDPOINT
            - name: OIDC_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: oidc-jwk-set-uri
                  key: OIDC_JWK_SET_URI
            - name: MATOMO_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: matomo-enabled
                  key: MATOMO_ENABLED
            - name: MATOMO_URL
              valueFrom:
                configMapKeyRef:
                  name: matomo-url
                  key: MATOMO_URL
            - name: MATOMO_SITE_ID
              valueFrom:
                configMapKeyRef:
                  name: matomo-site-id
                  key: MATOMO_SITE_ID
            - name: AGROPORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agroportal-api-key
                  key: AGROPORTAL_API_KEY
            - name: EARTHPORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: earthportal-api-key
                  key: EARTHPORTAL_API_KEY
            - name: BIODIVPORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: biodivportal-api-key
                  key: BIODIVPORTAL_API_KEY
            - name: ECOPORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ecoportal-api-key
                  key: ECOPORTAL_API_KEY
            - name: LOVPORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lovportal-api-key
                  key: LOVPORTAL_API_KEY
            - name: BIOPORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bioportal-api-key
                  key: BIOPORTAL_API_KEY
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=70"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi

