apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.images.frontend }}
          env:
            - name: ONTOPORTAL_APIKEY
              valueFrom:
                secretKeyRef:
                  name: ontoportal-secret
                  key: ONTOPORTAL_APIKEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.database }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-password
                  key: ADMIN_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 8080
