apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.images.frontend }}
        env:
          - name: ONTOPORTAL_APIKEY
            valueFrom:
              secretKeyRef:
                name: ontoportal-secret
                key: ONTOPORTAL_APIKEY
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgres.database }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.postgres.username }}
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
        ports:
          - containerPort: 8080
