apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-backend
        project: ts4nfdi
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: ts4nfdi-gateway
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-postgres 5432; do echo waiting for postgres; sleep 2; done' ]
      containers:
        - name: api-gateway
          image: {{ .Values.images.backend }}
          env:
            - name: ONTOPORTAL_APIKEY
              valueFrom:
                secretKeyRef:
                  name: ontoportal-secret
                  key: ONTOPORTAL_APIKEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.database }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-password
                  key: ADMIN_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 1000Mi

