{{- if .Values.ingress.redirectDns }}
  {{- $relname := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-redirect
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://{{ .Values.ingress.dns }}
spec:
  rules:
    - host: {{ .Values.ingress.redirectDns }}
      http:
        paths:
          - path: /api-gateway
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 80
{{- end }}