apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    project: ts4nfdi
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts4nfdi-gateway
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    name: {{ .Release.Name }}-backend