apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  teamId: "{{ .Release.Name }}"
  volume:
    size: 1Gi
  numberOfInstances: 2
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
  users:
    gateway:
      - superuser
      - createdb
  databases:
    db: gateway
  preparedDatabases:
    db: {}
  postgresql:
    version: "16"
