apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  teamId: "{{ .Release.Name }}"
  volume:
    size: 1Gi
  numberOfInstances: 2
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
  users:
    gateway:  # Ensure user is correctly defined
      - superuser
      - createdb
  databases:
    gateway: gateway  # Ensure the database is correctly linked to the user
  preparedDatabases:
    gateway: {}  # Matches the database name to ensure it's prepared
  postgresql:
    version: "14"
